spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shipping
    username: root
    password: root1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect


  security:
#    jwt:
#      secret-key: f53cabf7-a296-4272-9758-fb302c713d87
    user:
      roles:

auth:
  jwt:
    secret-key: f53cabf7-a296-4272-9758-fb302c713d87